server:
  servlet:
    context-path: /rtr
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: rtr-backend
  datasource:
    poolSize: 20
    minIdle: 1
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5431/rtr
    username: rtr
    password: password
    tomcat:
      test-while-idle: true
      test-on-borrow: true
      validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false

app:
  rmbt:
    duration: 7
    pings: 10
    threads: 3
    version: 0.1.0 || 0.3.0 || ^1.0.0
    language:
      supportedLanguages:
        - de
        - en
        - hr
        - sv
        - pl
        - es
        - is
        - fr
        - nb
        - cs
      defaultLanguage: en
    clientNames:
      - RMBT
      - RMBTjs
      - Open-RMBT
      - RMBTws
      - HW-PROBE

elastic-index:
  basicTenantIndexes:
    rtr: basic_test_rtr
  basicQosTenantIndexes:
    rtr: basic_qos_test_rtr
  keepAlive: keep_alive

client-tenant:
  clientTenantMapping:
    rtr: rtr
  defaultTenant: rtr

measurement-server:
  host: http://localhost:8080
  slotWindow: 5
  defaultProviderId: 6

jira:
  requestTypeId: 49
  serviceDeskId: 6
  url: https://specure.atlassian.net
  username: batalin.a@dbbest.com
  password: SuperSecurePassword

---
spring:
  profiles: dev
  datasource:
    poolSize: 20
    minIdle: 1
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URI}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    tomcat:
      test-while-idle: true
      test-on-borrow: true
      validation-query: SELECT 1

measurement-server:
  host: api-test.nettest.org

client-tenant:
  clientTenantMapping:
    rtr: rtr_dev
  defaultTenant: rtr

git:
  branch:${git.branch}